In [ ]:
# Numpy is powerful becuase it internals are actualy developed using c and c++ , so it is very good in performance than lists and python DS.
https://numpy.org/doc/stable/reference/routines.array-creation.html

In [ ]:
# Numpy Crash Course

In [2]:
import numpy as np

In [3]:
np.__version__

'2.0.2'

In [4]:
import sys
sys.version

'3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]'

## Creating LIST

In [5]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [ ]:
type(my_list)

list

# below code we are converting list to array

In [ ]:
#!pip install numpy

In [8]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [9]:
type(arr)

numpy.ndarray

In [ ]:
type(my_list)

list

In [ ]:
np. # we learn important function  ctrl_space will show you available functions

# arange method
numpy.arange([start, ]stop, [step, ]dtype=None, *, device=None, like=None)

In [ ]:
np.arange(10) # only stop

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [ ]:
np.arange(0, 5)  # start , stop

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(20,10) # 1st arg < 2nd arg

array([], dtype=int64)

In [ ]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [12]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [13]:
np.arange(30,20)  # 1st arg always be < then 2nd arg

array([], dtype=int64)

In [15]:
np.arange(10,10)

array([], dtype=int64)

In [16]:
np.arange()  #stop param is mandatory

TypeError: arange() requires stop to be specified.

In [18]:
np.arange(10,30,5)  # 10- starting from , 30- end point  , 5 - step count

array([10, 15, 20, 25])

In [19]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [ ]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [21]:
np.arange(10,30,5, dtype=int)

array([10, 15, 20, 25])

# zeros method
numpy.zeros(shape, dtype=None, order='C', *, device=None, like=None)

shape = ([row,]column)

by default 1 row when row is not defined

In [20]:
np.zeros(10) # parameter  tunning , 1 tow by default, 10 columns

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros(5, dtype=int) # hyperparameter tunning

array([0, 0, 0, 0, 0])

In [23]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [24]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [25]:
zero = np.zeros([2,2])
print(zero)

print('####')

print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [26]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [28]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((10,30))

In [ ]:
np.zeros((10,10),dtype = int)

In [30]:
np.zeros((5,10)) # bydefaul 1arge -- will give row & 2nd arg - columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) # parameter tunnin g

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [32]:
print(np.zeros(n,dtype=int)) ## hypyerparameter tunning

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [ ]:
print(np.zeros(n1))

# ones
numpy.ones(shape, dtype=None, order='C', *, device=None, like=None)

shape = ([row,]column)

In [ ]:
np.ones(3)

In [ ]:
np.ones((3,3))

In [ ]:
np.ones(4, dtype=int)

In [ ]:
np.ones(4)

In [ ]:
n

In [ ]:
np.ones(n)

In [ ]:
np.ones((5,4),dtype=int) # by default 5- rows & 4 - columns

In [ ]:
np.

In [ ]:
np.two((2,3))

In [ ]:
np.three(2,3)

In [ ]:
np.ones(2)

In [ ]:
np.ones((2,4))

In [ ]:
np.ones((6,10),dtype = int)

In [ ]:
np.twos((2,4))

In [ ]:
np.

In [ ]:
np.three((2,4))

In [ ]:
range(5)

In [ ]:
r = range(5)
r

In [ ]:
for i in r:
    print(i)

In [ ]:
list(range(5))

In [ ]:
range(1,10)

In [ ]:
list(range(1,10))

In [ ]:
list(range(1,10,3))

In [ ]:
y = list(range(12))
y

In [ ]:
rand(3,2)

In [ ]:
random.rand(3,2)

In [ ]:
np.random.rand(5)

In [ ]:
np.rand(4)

In [ ]:
np.random.rand(3,5)

In [ ]:
np.random.randint(4,6)

In [ ]:
np.random.randint(2,20,4) # 2nd argument is exlusive

In [ ]:
np.random.randint(0,1)

In [ ]:
np.random.randint(10,20,5)

In [ ]:
np.random.randint(1,6,4)

In [ ]:
np.random.rand(3)

In [ ]:
np.random.randint(1)

In [ ]:
np.random.randint(30,20,10)

In [ ]:
np.random.randint(-30,20,10)

In [ ]:
np.random.randint(20,30,10)

In [ ]:
np.random.randint(5,9)  #GET THE VALUE <=1 & >=5

In [ ]:
np.random.randint(10,21,3)

In [ ]:
np.random.randint(1,12,10)

In [ ]:
np.random.randint(10,40,(10,10)) #generre the element 10 -30 with 4*4 mtri

In [ ]:
np.random.randint(1,100,(12,12)) #generre the element 10 -30 with 4*4 mtri

In [ ]:
np.arange(1,13)

In [ ]:
np.arange(1,13).reshape(3,4)

In [ ]:
np.arange(1,13).reshape(4,3)

In [ ]:
np.arange(1,13).reshape(5,4)

In [ ]:
np.arange(1,13).reshape(6,2)

In [ ]:
np.arange(1,13).reshape(12,1)

# slicing in matrix

In [ ]:
b = np.random.randint(10,20,(5,4))
b

In [ ]:
type(b)

In [ ]:
b

In [ ]:
b[:]

In [ ]:
b[1:3]

In [ ]:
b

In [ ]:
b[1,2]

In [ ]:
b

In [ ]:
b[1,3]

In [ ]:
b

In [ ]:
b[1,-1]

In [ ]:
b

In [ ]:
b[2:3]

In [ ]:
b

In [ ]:
b[0:-2]

In [ ]:
b

In [ ]:
b[0,2]

In [ ]:
b

In [ ]:
b[-5,3]

In [ ]:
b[-5,-3]

In [ ]:
b

In [ ]:
b[-4,2]

In [ ]:
np.random.randint(10,20,(4,4))

In [ ]:
b

In [ ]:
b[-4,-2]

In [ ]:
b

In [ ]:
b[-4:2]

In [ ]:
b[:]

## Operations

In [ ]:
a = np.random.randint(10,20,10)
a

In [ ]:
id(a)

In [ ]:
arr

In [ ]:
arr2 = np.random.randint(0,100,(10,10))

In [ ]:
arr2

In [ ]:
arr

In [ ]:
arr[:]

In [ ]:
arr

In [ ]:
arr[:4]

In [ ]:
arr2[:]

In [ ]:
arr2[0:5]

In [ ]:
arr2

In [ ]:
arr2[1,4]

In [ ]:
arr2

In [ ]:
arr2[-5,5]

In [ ]:
arr2[-5,-5]

In [ ]:
arr2

In [ ]:
arr2[-5,-5]

In [ ]:
arr2

In [ ]:
arr2[-1,-2]

In [ ]:
arr2

In [ ]:
arr2[::-1]

In [ ]:
arr2

In [ ]:
arr2[::-2]

In [ ]:
arr2

In [ ]:
arr2[::-3]

In [ ]:
arr2

In [ ]:
arr2[:-3]

In [ ]:
arr2

In [ ]:
arr2[0:10:3]

In [ ]:
arr2

In [ ]:
arr2[3:]

In [ ]:
arr

In [ ]:
arr.max()

In [ ]:
arr.min()

In [ ]:
arr

In [ ]:
arr.mean()

In [ ]:
arr

In [ ]:
arr.median()

In [ ]:
from numpy import * # 256 function called internally
a = array([1,2,3,4,9])
median(a)

# Without work on import* can you please find the median, mode)

In [ ]:
arr

In [ ]:
arr.reshape(3,2)

In [ ]:
arr.reshape(6,1)

In [ ]:
arr.reshape(1,6)

In [ ]:
arr

In [ ]:
arr.reshape(2,4)

In [ ]:
arr

In [ ]:
arr.reshape(3,2,order='C')

In [ ]:
arr.reshape(2,3,order='C')

In [ ]:
arr.reshape(2,3,order='F') # print element with fortran

In [ ]:
arr.reshape(2,3,order='A') # A almost give you c type output

In [ ]:
# importing Numpy package
import numpy as np

# creating a Numpy array
num_array = np.arange(100).reshape(20, 5)
print(num_array)

# Display array in Fortran order

print("\n  C type array:")
for num_array in np.nditer(num_array, order="C"):
	print(num_array,end=' ')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]

  C type array:
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 

In [ ]:
# importing Numpy package
import numpy as np

# creating a Numpy array
num_array = np.arange(100).reshape(20, 5)
print(num_array)

# Display array in Fortran order

print("\n  C type array:")
for num_array in np.nditer(num_array, order="F"):
	print(num_array,end=' ')

In [ ]:
arr.

In [ ]:
arr.reshape(2,3)

In [ ]:
arr.reshape(1,4)

In [ ]:
arr.reshape(1,6)

In [ ]:
arr.reshape(6,1)

In [ ]:
arr.reshape(2,6)

In [ ]:
arr.reshape(3,3)

In [ ]:
arr

In [ ]:
arr.reshape(3,2)

## Indexing

In [ ]:
mat = np.arange(0,100).reshape(10,10)

In [ ]:
mat

In [ ]:
row = 4
col = 5

In [ ]:
col

In [ ]:
row

In [ ]:
mat

In [ ]:
mat[row,col]

In [ ]:
mat[4,5]

In [ ]:
mat

In [ ]:
mat[:]

In [ ]:
col = 6

In [ ]:
mat

In [ ]:
mat[7] # befault it represent to rows

In [ ]:
mat

In [ ]:
# With Slices
mat[:,col]

In [ ]:
mat

In [ ]:
mat[:, -1]

In [ ]:
mat

In [ ]:
mat[row,:]

In [ ]:
mat

In [ ]:
mat[:,8]

In [ ]:
mat

In [ ]:
mat[:col]

In [ ]:
mat[:6]

In [ ]:
row

In [ ]:
mat

In [ ]:
mat[:row]

In [ ]:
mat

In [ ]:
mat[row:]

In [ ]:
mat[:]

In [ ]:
mat[:,8]

In [ ]:
mat

In [ ]:
mat[:,-1]

In [ ]:
mat

In [ ]:
row

In [ ]:
col

In [ ]:
mat[:,col]

In [ ]:
mat

In [ ]:
mat[1,4]

In [ ]:
mat

In [ ]:
mat[1:4]

In [ ]:
mat

In [ ]:
mat[3:-3]

In [ ]:
mat

In [ ]:
mat[0]

In [ ]:
mat[6]

In [ ]:
mat

In [ ]:
mat[6:]

In [ ]:
mat[:6]

In [ ]:
mat

In [ ]:
mat[5:7]

In [ ]:
mat

In [ ]:
mat[0:10]

In [ ]:
mat

In [ ]:
mat[0:10:3]

In [ ]:
mat[0:10]

In [ ]:
mat[0:10:3]

In [ ]:
mat

In [ ]:
mat[4:]

In [ ]:
mat

In [ ]:
mat[:4]

In [ ]:
mat

In [ ]:
mat[::-1]

In [ ]:
mat

In [ ]:
mat[::-3]

In [ ]:
mat

In [ ]:
mat[::-3]

In [ ]:
mat

In [ ]:
mat[::-5]

In [ ]:
mat

In [ ]:
mat[2:6]

In [ ]:
mat

In [ ]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

In [ ]:
mat

In [ ]:
mat[0,1]

In [ ]:
mat[1,6]

In [ ]:
mat

In [ ]:
mat[1:6]

In [ ]:
mat[1:]

In [ ]:
mat

In [ ]:
mat[:6]

In [ ]:
mat[0:1]

In [ ]:
mat

In [ ]:
mat[3:5]

In [ ]:
mat[3,5]

In [ ]:
mat

In [ ]:
mat[1:2,2:4]

In [ ]:
mat

In [ ]:
mat[2:3,2:3]

In [ ]:
mat

In [ ]:
mat[2:4,3:5]

In [ ]:
mat[3:5,2:4]

In [ ]:
mat

In [ ]:
mat[2:3,4:5]

## Masking

In [ ]:
mat # we also called as filter

In [ ]:
id(mat)

In [ ]:
mat

In [ ]:
mat > 50

In [ ]:
mat[mat==50]

In [ ]:
mat

In [ ]:
mat == 50

In [ ]:
mat

In [ ]:
a1 = mat[mat<50]
a1

In [ ]:
mat

In [ ]:
a2 = mat[mat>50]
a2

In [ ]:
a3 = mat[mat<=50]
a3

In [ ]:
a4 = mat[mat==50]
a4

# python program to generat otp

In [ ]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")