In [ ]:
# Numpy is powerful becuase it internals are actualy developed using c and c++ , so it is very good in performance than lists and python DS.
https://numpy.org/doc/stable/reference/routines.array-creation.html

In [ ]:
# Numpy Crash Course

In [2]:
import numpy as np

In [3]:
np.__version__

'2.0.2'

In [4]:
import sys
sys.version

'3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]'

## Creating LIST

In [5]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [ ]:
type(my_list)

list

# array method
converts list to a array or matrix

numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, ndmax=0, like=None)


In [ ]:
#!pip install numpy

In [8]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [9]:
type(arr)

numpy.ndarray

In [ ]:
type(my_list)

list

In [ ]:
np. # we learn important function  ctrl_space will show you available functions

# arange method
numpy.arange([start, ]stop, [step, ]dtype=None, *, device=None, like=None)

Returns range of values as ndarray or matrix

In [ ]:
np.arange(10) # only stop

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [ ]:
np.arange(0, 5)  # start , stop

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(20,10) # 1st arg < 2nd arg

array([], dtype=int64)

In [ ]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [12]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [13]:
np.arange(30,20)  # 1st arg always be < then 2nd arg

array([], dtype=int64)

In [15]:
np.arange(10,10)

array([], dtype=int64)

In [16]:
np.arange()  #stop param is mandatory

TypeError: arange() requires stop to be specified.

In [18]:
np.arange(10,30,5)  # 10- starting from , 30- end point  , 5 - step count

array([10, 15, 20, 25])

In [19]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [ ]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [21]:
np.arange(10,30,5, dtype=int)

array([10, 15, 20, 25])

In [95]:
np.arange(1,5).reshape(2,2)

array([[1, 2],
       [3, 4]])

In [96]:
np.arange(1,6).reshape(2,2)

ValueError: cannot reshape array of size 5 into shape (2,2)

In [97]:
np.arange(1,4).reshape(2,2)

ValueError: cannot reshape array of size 3 into shape (2,2)

# zeros method
numpy.zeros(shape, dtype=None, order='C', *, device=None, like=None)

shape = ([row,]column)

by default 1 row when row is not defined

In [20]:
np.zeros(10) # parameter  tunning , 1 tow by default, 10 columns

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros(5, dtype=int) # hyperparameter tunning

array([0, 0, 0, 0, 0])

In [23]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [24]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [25]:
zero = np.zeros([2,2])
print(zero)

print('####')

print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [26]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [28]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((10,30))

In [ ]:
np.zeros((10,10),dtype = int)

In [30]:
np.zeros((5,10)) # bydefaul 1arge -- will give row & 2nd arg - columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) # parameter tunnin g

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [32]:
print(np.zeros(n,dtype=int)) ## hypyerparameter tunning

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [ ]:
print(np.zeros(n1))

# ones
numpy.ones(shape, dtype=None, order='C', *, device=None, like=None)

shape = ([row,]column)

In [34]:
np.ones(3)

array([1., 1., 1.])

In [35]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [ ]:
np.ones(4)

In [ ]:
np.ones((5,4),dtype=int) # by default 5- rows & 4 - columns

In [37]:
np.two((2,3))

AttributeError: module 'numpy' has no attribute 'two'

In [38]:
np.three(2,3)

AttributeError: module 'numpy' has no attribute 'three'

In [43]:
np.ones((6,10),dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [44]:
range(5)

range(0, 5)

In [45]:
r = range(5)
r

range(0, 5)

In [46]:
for i in r:
    print(i)

0
1
2
3
4


In [47]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
range(1,10)

In [48]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [49]:
list(range(1,10,3))

[1, 4, 7]

In [50]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

# numpy.random.rand  method
random.rand(d0, d1, ..., dn)

returns d01,d1.. dimentional matrix or array

In [52]:
random.rand(3,2)

NameError: name 'random' is not defined

In [ ]:
np.random.  #so many methods example rand , randint...

In [53]:

np.random.rand(5)

array([0.03277252, 0.07240882, 0.39227538, 0.68909094, 0.16973905])

In [55]:
np.random.rand(3,5)

array([[0.41035249, 0.64883629, 0.86870278, 0.4555352 , 0.12547656],
       [0.67497183, 0.27105521, 0.9791554 , 0.51007438, 0.05161966],
       [0.22953687, 0.69607136, 0.06418619, 0.87612536, 0.35909322]])

In [64]:
np.random.rand(3,4,2)

array([[[0.35341114, 0.86644737],
        [0.61227098, 0.81821124],
        [0.73341148, 0.63231737],
        [0.1564669 , 0.34825403]],

       [[0.56822566, 0.05896973],
        [0.98568734, 0.34921348],
        [0.10612734, 0.70389027],
        [0.82059622, 0.47773432]],

       [[0.94590667, 0.13605571],
        [0.71722817, 0.97389472],
        [0.61880321, 0.95002187],
        [0.92811566, 0.77608465]]])

# numpy.random.randint
random.randint(low, high=None, size=None, dtype=int)

Return random integers from low (inclusive) to high (exclusive).

In [84]:
np.random.randint(1) #always 0

0

In [88]:
np.random.randint(3) # choose 1 random value between 0-2

0

In [89]:
np.random.randint(4,6)  #random integer between 4 and 5

5

In [66]:
np.random.randint(2,20,4) # Random values b/w 2-19 , size 4 means 1 row , 4 cols , so 4 random values between 2-19

array([ 8, 14,  6, 12])

In [67]:
np.random.randint(0,1)

0

In [69]:
np.random.randint(10,20,5)

array([13, 14, 12, 12, 15])

In [ ]:
np.random.randint(30,20,10)

In [57]:
np.random.randint(-30,20,10)

array([  3,  -9,  18, -18,  17,   8, -28,   5, -18, -29])

In [ ]:
np.random.randint(20,30,10)

In [ ]:
np.random.randint(5,9)  #GET THE VALUE <=1 & >=5

In [ ]:
np.random.randint(10,21,3)

In [ ]:
np.random.randint(1,12,10)

In [90]:
np.random.randint(10,30,(4,4)) #generre the element 10 -29 with 4*4 mtri

array([[11, 27, 12, 28],
       [26, 16, 14, 13],
       [26, 25, 23, 27],
       [19, 16, 21, 23]])

In [ ]:
np.random.randint(1,100,(12,12)) #generre the element 10 -30 with 4*4 mtri

# slicing in matrix
[row_start:row_end_exclusive, col_start:,col_end_exclusive]

In [102]:
b = np.random.randint(10,20,(5,4))
b

array([[19, 13, 14, 13],
       [12, 19, 18, 14],
       [14, 17, 17, 13],
       [14, 15, 18, 16],
       [13, 11, 12, 11]])

In [103]:
type(b)

numpy.ndarray

In [ ]:
b

In [104]:
b[:]

array([[19, 13, 14, 13],
       [12, 19, 18, 14],
       [14, 17, 17, 13],
       [14, 15, 18, 16],
       [13, 11, 12, 11]])

In [105]:
b[1:3]  # 2nd and 3rd rows

array([[12, 19, 18, 14],
       [14, 17, 17, 13]])

In [106]:
b[1,2]  # 1-> 2nd row , 2-> 3rd column

np.int64(18)

In [ ]:
b

In [107]:
b[1,3]  # 2nd row, 4th column

np.int64(14)

In [108]:
b[1,-1] # 2nd  row , last column

np.int64(14)

In [109]:
b[2:3]

array([[14, 17, 17, 13]])

In [110]:
b

array([[19, 13, 14, 13],
       [12, 19, 18, 14],
       [14, 17, 17, 13],
       [14, 15, 18, 16],
       [13, 11, 12, 11]])

In [111]:
b[0:-2] # 1st row to last 2nd row

array([[19, 13, 14, 13],
       [12, 19, 18, 14],
       [14, 17, 17, 13]])

In [ ]:
b

In [ ]:
b[0,2]

In [ ]:
b

In [ ]:
b[-5,3]

In [ ]:
b[-5,-3]

In [ ]:
b

In [ ]:
b[-4,2]

In [ ]:
np.random.randint(10,20,(4,4))

In [ ]:
b

In [ ]:
b[-4,-2]

In [ ]:
b

In [ ]:
b[-4:2]

In [ ]:
b[:]

## Operations

In [112]:
a = np.random.randint(10,20,10)
a

array([15, 13, 13, 12, 19, 19, 19, 11, 14, 10])

In [113]:
id(a)

133198189980112

In [115]:
arr

array([0, 1, 2, 3, 4, 5])

In [117]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[28, 63, 12, 81, 55, 43, 54, 42, 90, 85],
       [69, 56, 48, 58, 97, 91, 96,  9, 60, 49],
       [83, 45, 48, 89, 34, 97, 15, 47, 39, 46],
       [ 9,  8, 19, 40, 98, 30, 80, 64,  8, 50],
       [ 0, 51, 69, 41, 82, 70, 30, 35, 10, 51],
       [44, 74, 61, 12, 29, 52, 15, 90, 82, 25],
       [35, 19, 48, 13, 94,  0, 96, 43,  7, 74],
       [46, 48, 25, 80, 86,  1, 47, 83, 31, 26],
       [90,  0,  3, 95,  9, 48, 29,  1, 47, 66],
       [91, 71, 62,  8, 40, 65, 86, 80, 27, 49]])

In [119]:
arr[:4]

array([0, 1, 2, 3])

In [120]:
arr[4]

np.int64(4)

In [121]:
arr2[:]

array([[28, 63, 12, 81, 55, 43, 54, 42, 90, 85],
       [69, 56, 48, 58, 97, 91, 96,  9, 60, 49],
       [83, 45, 48, 89, 34, 97, 15, 47, 39, 46],
       [ 9,  8, 19, 40, 98, 30, 80, 64,  8, 50],
       [ 0, 51, 69, 41, 82, 70, 30, 35, 10, 51],
       [44, 74, 61, 12, 29, 52, 15, 90, 82, 25],
       [35, 19, 48, 13, 94,  0, 96, 43,  7, 74],
       [46, 48, 25, 80, 86,  1, 47, 83, 31, 26],
       [90,  0,  3, 95,  9, 48, 29,  1, 47, 66],
       [91, 71, 62,  8, 40, 65, 86, 80, 27, 49]])

In [122]:
arr2[0:5]

array([[28, 63, 12, 81, 55, 43, 54, 42, 90, 85],
       [69, 56, 48, 58, 97, 91, 96,  9, 60, 49],
       [83, 45, 48, 89, 34, 97, 15, 47, 39, 46],
       [ 9,  8, 19, 40, 98, 30, 80, 64,  8, 50],
       [ 0, 51, 69, 41, 82, 70, 30, 35, 10, 51]])

In [123]:
arr2[1,4]

np.int64(97)

In [ ]:
arr2[-5,5]

In [124]:
arr2[-5,-5]

np.int64(52)

In [ ]:
arr2

In [ ]:
arr2[-5,-5]

In [ ]:
arr2

In [ ]:
arr2[-1,-2]

In [ ]:
arr2

In [ ]:
arr2[::-1]

In [ ]:
arr2

In [ ]:
arr2[::-2]

In [ ]:
arr2

In [ ]:
arr2[::-3]

In [ ]:
arr2

In [ ]:
arr2[:-3]

In [ ]:
arr2

In [ ]:
arr2[0:10:3]

In [ ]:
arr2

In [ ]:
arr2[3:]

In [126]:
arr

array([0, 1, 2, 3, 4, 5])

In [127]:
arr.max()

np.int64(5)

In [128]:
arr.min()

np.int64(0)

In [ ]:
arr

In [129]:
arr.mean()

np.float64(2.5)

In [ ]:
arr

In [130]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [131]:
from numpy import * # 256 function called internally
a = array([1,2,3,4,9])
median(a)

np.float64(3.0)

# Without work on import* can you please find the median, mode)

In [ ]:
arr

In [ ]:
arr.reshape(3,2)

In [ ]:
arr.reshape(6,1)

In [ ]:
arr.reshape(1,6)

In [ ]:
arr

In [ ]:
arr.reshape(2,4)

In [ ]:
arr

In [ ]:
arr.reshape(3,2,order='C')

In [ ]:
arr.reshape(2,3,order='C')

In [ ]:
arr.reshape(2,3,order='F') # print element with fortran

In [ ]:
arr.reshape(2,3,order='A') # A almost give you c type output

In [ ]:
# importing Numpy package
import numpy as np

# creating a Numpy array
num_array = np.arange(100).reshape(20, 5)
print(num_array)

# Display array in Fortran order

print("\n  C type array:")
for num_array in np.nditer(num_array, order="C"):
	print(num_array,end=' ')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]

  C type array:
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 

In [ ]:
# importing Numpy package
import numpy as np

# creating a Numpy array
num_array = np.arange(100).reshape(20, 5)
print(num_array)

# Display array in Fortran order

print("\n  C type array:")
for num_array in np.nditer(num_array, order="F"):
	print(num_array,end=' ')

In [ ]:
arr.

In [ ]:
arr.reshape(2,3)

In [ ]:
arr.reshape(1,4)

In [ ]:
arr.reshape(1,6)

In [ ]:
arr.reshape(6,1)

In [ ]:
arr.reshape(2,6)

In [ ]:
arr.reshape(3,3)

In [ ]:
arr

In [ ]:
arr.reshape(3,2)

## Indexing

In [ ]:
mat = np.arange(0,100).reshape(10,10)

In [ ]:
mat

In [ ]:
row = 4
col = 5

In [ ]:
col

In [ ]:
row

In [ ]:
mat

In [ ]:
mat[row,col]

In [ ]:
mat[4,5]

In [ ]:
mat

In [ ]:
mat[:]

In [ ]:
col = 6

In [ ]:
mat

In [ ]:
mat[7] # befault it represent to rows

In [ ]:
mat

In [ ]:
# With Slices
mat[:,col]

In [ ]:
mat

In [ ]:
mat[:, -1]

In [ ]:
mat

In [ ]:
mat[row,:]

In [ ]:
mat

In [ ]:
mat[:,8]

In [ ]:
mat

In [ ]:
mat[:col]

In [ ]:
mat[:6]

In [ ]:
row

In [ ]:
mat

In [ ]:
mat[:row]

In [ ]:
mat

In [ ]:
mat[row:]

In [ ]:
mat[:]

In [ ]:
mat[:,8]

In [ ]:
mat

In [ ]:
mat[:,-1]

In [ ]:
mat

In [ ]:
row

In [ ]:
col

In [ ]:
mat[:,col]

In [ ]:
mat

In [ ]:
mat[1,4]

In [ ]:
mat

In [ ]:
mat[1:4]

In [ ]:
mat

In [ ]:
mat[3:-3]

In [ ]:
mat

In [ ]:
mat[0]

In [ ]:
mat[6]

In [ ]:
mat

In [ ]:
mat[6:]

In [ ]:
mat[:6]

In [ ]:
mat

In [ ]:
mat[5:7]

In [ ]:
mat

In [ ]:
mat[0:10]

In [ ]:
mat

In [ ]:
mat[0:10:3]

In [ ]:
mat[0:10]

In [ ]:
mat[0:10:3]

In [ ]:
mat

In [ ]:
mat[4:]

In [ ]:
mat

In [ ]:
mat[:4]

In [ ]:
mat

In [ ]:
mat[::-1]

In [ ]:
mat

In [ ]:
mat[::-3]

In [ ]:
mat

In [ ]:
mat[::-3]

In [ ]:
mat

In [ ]:
mat[::-5]

In [ ]:
mat

In [ ]:
mat[2:6]

In [ ]:
mat

In [ ]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

In [ ]:
mat

In [ ]:
mat[0,1]

In [ ]:
mat[1,6]

In [ ]:
mat

In [ ]:
mat[1:6]

In [ ]:
mat[1:]

In [ ]:
mat

In [ ]:
mat[:6]

In [ ]:
mat[0:1]

In [ ]:
mat

In [ ]:
mat[3:5]

In [ ]:
mat[3,5]

In [ ]:
mat

In [ ]:
mat[1:2,2:4]

In [ ]:
mat

In [ ]:
mat[2:3,2:3]

In [ ]:
mat

In [ ]:
mat[2:4,3:5]

In [ ]:
mat[3:5,2:4]

In [ ]:
mat

In [ ]:
mat[2:3,4:5]

## Masking

In [ ]:
mat # we also called as filter

In [ ]:
id(mat)

In [ ]:
mat

In [ ]:
mat > 50

In [ ]:
mat[mat==50]

In [ ]:
mat

In [ ]:
mat == 50

In [ ]:
mat

In [ ]:
a1 = mat[mat<50]
a1

In [ ]:
mat

In [ ]:
a2 = mat[mat>50]
a2

In [ ]:
a3 = mat[mat<=50]
a3

In [ ]:
a4 = mat[mat==50]
a4

# python program to generat otp

In [134]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 5023
